### ISSUE TITLE
Node 0.10.x compat

### ISSUE THREAD

**Issue by atrefz** [jeremyfa/node-exec-sync#18]
The install of this module works under 0.8.22 but fails under 0.10.0 as well as 0.10.1 for me (OS X) here is the log:
```
> ref@0.1.3 install /Users/atrefz/Documents/Projekte/Karbon/node_modules/ss-toffee/node_modules/exec-sync/node_modules/ffi/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node: Finished

> ffi@1.1.2 install /Users/atrefz/Documents/Projekte/Karbon/node_modules/ss-toffee/node_modules/exec-sync/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
In file included from ../deps/libffi/src/closures.c:210:
../deps/libffi/src/dlmalloc.c:3391:30: warning: expression result unused [-Wunused-value]
  set_segment_flags(&m->seg, mmapped);
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../deps/libffi/src/dlmalloc.c:1957:39: note: expanded from macro 'set_segment_flags'
  (((v) != IS_MMAPPED_BIT) ? (ABORT, (v)) :                             \
                                      ^
../deps/libffi/src/dlmalloc.c:3551:34: warning: expression result unused [-Wunused-value]
      set_segment_flags(&m->seg, mmap_flag);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
../deps/libffi/src/dlmalloc.c:1957:39: note: expanded from macro 'set_segment_flags'
  (((v) != IS_MMAPPED_BIT) ? (ABORT, (v)) :                             \
                                      ^
2 warnings generated.
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc:284:3: error: no matching function for call to 'uv_queue_work'
  uv_queue_work(uv_default_loop(), req,
  ^~~~~~~~~~~~~
/Users/atrefz/.node-gyp/0.10.1/deps/uv/include/uv.h:1397:15: note: candidate function not viable: no known conversion from 'void (uv_work_t *)' to 'uv_after_work_cb'
      (aka 'void (*)(uv_work_t *, int)') for 4th argument;
UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
              ^
1 error generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 12.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/atrefz/Documents/Projekte/Karbon/node_modules/ss-toffee/node_modules/exec-sync/node_modules/ffi
gyp ERR! node -v v0.10.1
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok
npm ERR! ffi@1.1.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the ffi@1.1.2 install script.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/atrefz/Documents/Projekte/Karbon
npm ERR! node -v v0.10.1
npm ERR! npm -v 1.2.15
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/atrefz/Documents/Projekte/Karbon/npm-debug.log
npm ERR! not ok code 0
```

**Comment by bitlinguist** [comment]
This is really funny, this repo is not maintained but the above mentioned is also not being maintained. I wish I knew more about NPM and Node because I am getting the same error as above. My env is setup with Node v 0.12.3 and npm 2.9.3. I'll be notifying here if I happen to come to a fix.

**Comment by jeremyfa** [comment]
execSync is now available in node v0.12 standard library. No need to use a third-party library

**Comment by dewwwald** [comment]
Thanks @jeremyfa, I'll take this up with them as their package also does not work on my system.

**Comment by dewwwald** [comment]
Oh I understand now! You meant built in already. Thanks!
